export type Locale = "es" | "en";

export const LOCALES = ["es", "en"] as const;

export function isLocale(value: string | null): value is Locale {
  return value === "es" || value === "en";
}

export const copy = {
  es: {
    nav: {
      primary: "Navegación principal",
      work: "WORK",
      lab: "LAB",
      about: "PERFIL",
      stats: "EN NÚMEROS",
      projects: "PROYECTOS",
      timeline: "TRAYECTORIA",
      optimizer: "OPTIMIZER",
      contact: "CONTACTO",
      lang: "Idioma",
      es: "Español",
      en: "English",
      remote: "REMOTE",
      menu: "MENÚ",
    },
    ticker: {
      label: "SEÑALES",
      items: [
        { label: "PRODUCTO", value: "Fintech en producción" },
        { label: "BASE", value: "Salta · Argentina" },
        { label: "MODO", value: "Full-remote" },
        { label: "OUTPUT", value: "4 productos públicos" },
        { label: "AHORA", value: "Construyendo producto" },
      ],
    },
    hero: {
      tag: "SALTA · ARGENTINA  //  ABIERTO A ROLES FULL-REMOTE",
      identity: "LUCIANO LAZARTE · FULL STACK / PRODUCT",
      title: "Diseño y construyo productos fintech que la gente puede usar.",
      lead: "Full Stack Developer. Construyo un producto de inversión retail para que gente sin experiencia financiera pueda invertir. React y TypeScript en el frontend, NestJS y GraphQL en el backend.",
      ctaWork: "VER PROYECTOS",
      ctaContact: "CONTACTARME",
      consoleLabel: "OPERATOR PROFILE / 01",
      consoleStatus: "PRUEBA VERIFICABLE",
      portraitRole: "FULL STACK · PRODUCT · FINTECH",
      proof: [
        { value: "EN PROD", label: "Producto fintech de inversión retail" },
        { value: "04", label: "Productos públicos con demo" },
        { value: "1°", label: "Puna Tech 2026 · City Track" },
      ],
      model: {
        label: "MODEL / INTERFACE PREVIEW",
        note: "Visual conceptual · no es información de mercado en vivo",
        alt: "Visualización conceptual de una interfaz de producto",
      },
      phrases: [
        "Construyo producto fintech full stack, de punta a punta.",
        "React y TypeScript adelante. NestJS y GraphQL atrás.",
        "Inversión retail para gente que nunca invirtió.",
      ],
      meta: [
        { label: "ROL", val: "Full Stack Developer" },
        { label: "FOCO", val: "Fintech · Producto" },
        { label: "STACK", val: "React · TypeScript · NestJS · GraphQL" },
        { label: "UBICACIÓN", val: "Salta, Argentina" },
        { label: "DISPONIBILIDAD", val: "Full-remote" },
      ],
    },
    about: {
      title: "SOBRE MÍ",
      badge: "// PERFIL",
      p1: "Soy estudiante de Ingeniería Informática en UCASAL y Full Stack Developer con foco en fintech. Invierto en el mercado de capitales desde hace algunos años — eso me da contexto real sobre qué problemas vale la pena resolver con software.",
      p2: "Actualmente trabajo en Poncho Capital como Full Stack Developer, Product. Construyo un producto de inversión retail para gente sin experiencia financiera: React y TypeScript en el frontend, NestJS y GraphQL en el backend, flujos web de punta a punta.",
      p3: "Antes trabajé como Data Analyst freelance (Python, SQL, Power BI). Los proyectos que muestro acá los construí y los uso yo mismo.",
      identity: "IDENTIDAD",
      photoAlt: "Foto de Luciano Lazarte",
      cards: [
        {
          label: "FOCO ACTUAL",
          items: [
            "Producto de inversión retail en Poncho Capital",
            "React y TypeScript en el frontend, NestJS y GraphQL en el backend",
            "Flujos web de punta a punta en un equipo chico",
          ],
        },
        {
          label: "BUSCANDO",
          items: [
            "Roles full-remote de Full Stack / Product",
            "Fintech donde el producto se use de verdad",
            "Equipos chicos con ownership de punta a punta",
          ],
        },
        {
          label: "FORMACIÓN",
          items: [
            "Ingeniería Informática · UCASAL · en curso",
            "Data Scientist · Coderhouse",
            "Data Analytics · Coderhouse",
          ],
        },
      ],
    },
    stats: {
      title: "PRUEBA DE TRABAJO",
      badge: "// 03 SEÑALES VERIFICABLES",
      items: [
        {
          value: "PROD",
          label: "PRODUCTO FINTECH",
          sub: "Poncho Capital · inversión retail",
          detail: "Flujos web de punta a punta en producción",
        },
        {
          value: "04",
          label: "PRODUCTOS PÚBLICOS",
          sub: "Ink · QuantLab · Cello · EstacionaSalta",
          detail: "Demos vivas, no mockups",
        },
        {
          value: "1°",
          label: "PUNA TECH 2026",
          sub: "City Track · EstacionaSalta",
          detail: "Producto de estacionamiento medido para Salta",
        },
      ],
    },
    github: {
      title: "ACTIVIDAD",
      badge: "// GITHUB · JEHP23",
      contributions: "CONTRIBUCIONES · ÚLTIMOS 12 MESES",
      chartAlt: "Gráfico de contribuciones en GitHub",
      repos: (n: number) => `${n} repos públicos`,
      since: (year: string) => `activo desde ${year}`,
      languages: "LENGUAJES",
      recent: "ACTIVIDAD RECIENTE",
      today: "hoy",
      yesterday: "ayer",
      days: (n: number) => `hace ${n}d`,
      weeks: (n: number) => `hace ${n}sem`,
      months: (n: number) => `hace ${n}m`,
    },
    projects: {
      title: "PROYECTOS & FOCO",
      badge: "// QUÉ HAGO Y EN QUÉ TRABAJO",
      intro: "Trabajo seleccionado, ordenado por impacto de producto: de flujos en producción a experimentos públicos que se pueden probar.",
      caseLabel: "Casos principales",
      selectedLabel: "PRODUCTOS SELECCIONADOS",
      archiveLabel: "ARCHIVO / LAB",
      items: [
        {
          id: "poncho",
          rarity: "legendary",
          tag: "FLAGSHIP · PRODUCCIÓN",
          title: "Poncho Capital · Retail Investing",
          desc: "Producto de inversión para gente sin experiencia financiera. Trabajo el stack de punta a punta en un equipo chico: React y TypeScript en el frontend, NestJS y GraphQL en el backend. Flujos web en producción.",
          stack: ["React", "TypeScript", "NestJS", "GraphQL"],
          stats: [
            { s: "ROL", v: "FULL STACK" },
            { s: "ESTADO", v: "EN PROD" },
          ],
          links: [{ label: "Sitio", href: "https://ponchocapital.com" }],
        },
        {
          id: "estacionasalta",
          rarity: "legendary",
          tag: "1° PUNA TECH 2026 · CITY TRACK",
          title: "EstacionaSalta · Estacionamiento medido",
          desc: "Producto de estacionamiento medido para la ciudad de Salta. Primer puesto en Puna Tech 2026, City Track.",
          stack: ["TypeScript", "React", "Next.js"],
          stats: [
            { s: "PREMIO", v: "1° PUESTO" },
            { s: "TRACK", v: "CITY" },
          ],
          links: [
            { label: "Demo", href: "https://estacionasalta.vercel.app" },
            { label: "Video", href: "https://www.youtube.com/watch?v=ThcJASSvIPU" },
          ],
        },
        {
          id: "ink",
          rarity: "epic",
          tag: "AVALANCHE · FINTECH",
          title: "INK · Smart Contract Risk Intelligence",
          desc: "Analizador de riesgo de smart contracts. Ingresás una dirección y el sistema devuelve un score determinístico 0–100 más una explicación en lenguaje natural.",
          stack: ["Next.js", "TypeScript", "Avalanche"],
          stats: [
            { s: "TIPO", v: "LIVE PRODUCT" },
            { s: "SCORE", v: "0–100" },
          ],
          links: [
            { label: "Demo", href: "https://ink-three-iota.vercel.app" },
            { label: "GitHub", href: "https://github.com/Jehp23/ink-risk-intelligence" },
          ],
        },
        {
          id: "cello",
          rarity: "epic",
          tag: "AVALANCHE · PAGOS",
          title: "Cello · Pagos institucionales",
          desc: "Pagos institucionales privados usando eERC20 en Avalanche.",
          stack: ["TypeScript", "Avalanche", "eERC20"],
          stats: [
            { s: "TIPO", v: "LIVE PRODUCT" },
            { s: "RED", v: "AVALANCHE" },
          ],
          links: [{ label: "Demo", href: "https://cello-avax.vercel.app" }],
        },
        {
          id: "quantlab",
          rarity: "epic",
          tag: "FINTECH · RESEARCH",
          title: "QuantLab · Quant Research Platform",
          desc: "Plataforma de research cuantitativo: VaR, Monte Carlo, frontera eficiente y opciones BYMA.",
          stack: ["FastAPI", "Python", "Next.js", "TypeScript"],
          stats: [
            { s: "MERCADO", v: "ARG + GLOBAL" },
            { s: "MÓDULOS", v: "VAR · MC · BYMA" },
          ],
          links: [
            { label: "Demo", href: "https://quantlab2.vercel.app" },
            { label: "Backend", href: "https://github.com/Jehp23/quantlab-back" },
            { label: "Frontend", href: "https://github.com/Jehp23/quantlab-front" },
          ],
        },
        {
          id: "credit",
          rarity: "rare",
          tag: "DATA SCIENCE · ML",
          title: "Riesgo Crediticio · ML Ensemble",
          desc: "Predicción de incumplimiento de préstamos: EDA, SMOTE, PCA y ensemble de XGBoost, Random Forest, Gradient Boosting y Voting Classifier. AUC 0.942.",
          stack: ["Python", "XGBoost", "scikit-learn", "SMOTE"],
          stats: [
            { s: "AUC", v: "0.942" },
            { s: "MODELOS", v: "4 + ENSEMBLE" },
          ],
          links: [
            { label: "GitHub", href: "https://github.com/Jehp23/riesgo-crediticio" },
          ],
        },
      ],
    },
    timeline: {
      title: "EXPERIENCIA & FORMACIÓN",
      badge: "// TRAYECTORIA",
      items: [
        {
          id: "poncho",
          yr: "Mar 2026 · Actual",
          role: "Full Stack Developer, Product · Poncho Capital",
          desc: "Construyo un producto de inversión retail para que gente sin experiencia financiera pueda invertir. Shippeo features de punta a punta: React y TypeScript en el frontend, NestJS y GraphQL en el backend.",
          tags: ["React", "TypeScript", "NestJS", "GraphQL"],
        },
        {
          id: "freelance",
          yr: "Nov 2024 – Jul 2026",
          role: "Data Analyst · Freelance",
          desc: "Análisis y dashboards en Python, SQL y Power BI. Pasé datasets crudos a reportes que se usaron para decisiones financieras y operativas.",
          tags: ["Python", "SQL", "Power BI"],
        },
        {
          id: "own",
          yr: "2025 · 2026",
          role: "Proyectos propios · Fintech y producto",
          desc: "INK (riesgo de smart contracts), QuantLab (research cuantitativo), Cello (pagos institucionales privados) y EstacionaSalta (1° puesto, Puna Tech 2026 · City Track).",
          tags: ["TypeScript", "Avalanche", "Python", "Producto"],
        },
        {
          id: "coderhouse",
          yr: "Jun 2024 · Nov 2023",
          role: "Data Scientist · Data Analytics · Coderhouse",
          desc: "Formación en ML, estadística aplicada, análisis exploratorio y narrativa con datos. Base para trabajar con números de mercado sin inventar.",
          tags: ["Python", "SQL", "Power BI", "ML"],
        },
        {
          id: "ucasal",
          yr: "2023 – 2028",
          role: "Ingeniería Informática · UCASAL",
          desc: "En curso. Fundamentos: estructuras de datos, algoritmos, sistemas operativos, arquitectura de software y redes.",
          tags: ["CS", "Algoritmos", "Sistemas", "Arquitectura"],
        },
      ],
    },
    contact: {
      eyebrow: "¿CONSTRUIMOS ALGO QUE IMPORTE?",
      title: "Hablemos de producto, no sólo de tickets.",
      body: "Abierto a roles full-remote de Full Stack / Product en fintech. React, TypeScript, NestJS, GraphQL. Si estás construyendo producto de verdad, escribime.",
      blink: "ABIERTO A ROLES FULL-REMOTE · ACTUALMENTE EN PONCHO CAPITAL",
    },
    footer: {
      updated: "Actualizado",
    },
    optimizerCta: {
      label: "PRODUCT LAB · PLAYABLE PROOF",
      title: "No sólo te cuento cómo pienso producto. Podés probarlo.",
      desc: "Ingresá tus activos con el peso actual, visualizá tu composición y calculamos la distribución óptima usando la teoría de Markowitz con Monte Carlo.",
      button: "OPTIMIZAR CARTERA →",
      points: [
        "Modelo media-varianza",
        "8.000 simulaciones Monte Carlo",
        "Herramienta educativa con datos en ARS",
      ],
      previewLabel: "MODEL / INTERFACE PREVIEW",
      previewMode: "STATIC PREVIEW",
      previewAlt: "Vista previa conceptual de la frontera eficiente del optimizador",
      previewStats: [
        { label: "SIMULACIONES", value: "8.000" },
        { label: "MODELO", value: "MARKOWITZ" },
        { label: "ALCANCE", value: "EDUCATIVO" },
      ],
      close: "Cerrar optimizador",
    },
    opt: {
      title: "OPTIMIZADOR DE CARTERA",
      badge: "// MARKOWITZ · FRONTERA EFICIENTE",
      intro: (n: string, days: number) =>
        `Modelo media-varianza (Markowitz, 1952) · ${n} simulaciones Monte Carlo · Retornos logarítmicos anualizados (${days} días) · Precios en ARS · Fuente: data912.com`,
      composition: "COMPOSICIÓN ACTUAL",
      asset: "ACTIVO",
      weight: "PONDERACIÓN (%)",
      placeholder: "Ej: GGAL",
      add: "+ Agregar activo",
      rf: "TASA LIBRE DE RIESGO ANUAL (rf)",
      rfUnit: "% anual nominal",
      rfHint: "Para activos en ARS se sugiere usar la tasa de referencia BCRA o rendimiento de LECAP.",
      calc: "CALCULAR FRONTERA EFICIENTE →",
      calculating: "CALCULANDO...",
      needMore: (n: string) => `Faltan ${n}pp para completar la cartera.`,
      tooMuch: (n: string) => `La cartera excede el 100% por ${n}pp.`,
      minAssets: "Ingresá al menos 2 activos.",
      errMin: "Necesitás al menos 2 activos.",
      errWeights: (n: string) => `Los pesos deben sumar 100%. Ahora: ${n}%.`,
      errData: "Error al obtener datos.",
      errConn: "Error de conexión. Intentá de nuevo.",
      supports:
        "Soporta acciones BYMA (GGAL, YPFD, BMA…), CEDEARs (AAPL, MSFT, TSLA…) y bonos soberanos (AL30, GD30…).",
      distribution: "DISTRIBUCIÓN ACTUAL",
      stats: "ESTADÍSTICAS INDIVIDUALES · ACTIVOS",
      statHeaders: [
        "ACTIVO",
        "RETORNO ESPERADO (E[r])",
        "DESV. ESTÁNDAR (σ)",
        "SHARPE INDIVIDUAL",
        "PESO ACTUAL",
      ],
      currentPortfolio: "CARTERA ACTUAL",
      sharpeNote: (rf: string, days: number) =>
        `Sharpe = (E[r] − rf) / σ · rf = ${rf} · Retornos logarítmicos anualizados sobre ${days} observaciones diarias.`,
      corr: "MATRIZ DE CORRELACIONES",
      corrNote:
        "Correlaciones de Pearson sobre retornos logarítmicos diarios. Valores cercanos a 0 implican mayor beneficio de diversificación.",
      frontier: "FRONTERA EFICIENTE · ESPACIO RIESGO-RETORNO",
      frontierNote:
        "Cada punto representa un portfolio con ponderaciones aleatorias. Color: rojo (bajo Sharpe) → verde (alto Sharpe). La CML conecta la tasa libre de riesgo con la cartera tangente — portafolios sobre la CML son inalcanzables sin apalancamiento.",
      recs: "CARTERAS SUGERIDAS",
      recItems: [
        { label: "★ CARTERA TANGENTE", sub: "Máximo ratio de Sharpe" },
        { label: "◆ CARTERA MODERADA", sub: "Sharpe intermedio" },
        { label: "● MÍN. VARIANZA GLOBAL", sub: "Mínimo riesgo (GMV)" },
      ],
      disclaimer:
        "Optimización basada en retornos históricos de los últimos ~12 meses. Los retornos pasados no garantizan resultados futuros. No constituye asesoramiento de inversión. Herramienta de carácter educativo.",
      chartYours: "TU CARTERA",
      chartX: "RIESGO — DESVIACIÓN ESTÁNDAR ANUALIZADA",
      chartY: "RETORNO ESPERADO ANUALIZADO",
      chartLegend: [
        "★  Cartera Tangente (Máx. Sharpe)",
        "●  Mínima Varianza Global (GMV)",
        "●  Cartera Moderada",
        "○  Tu cartera actual",
        "- -  Línea de Mercado de Capitales (CML)",
      ],
    },
  },
  en: {
    nav: {
      primary: "Primary navigation",
      work: "WORK",
      lab: "LAB",
      about: "PROFILE",
      stats: "NUMBERS",
      projects: "WORK",
      timeline: "PATH",
      optimizer: "OPTIMIZER",
      contact: "CONTACT",
      lang: "Language",
      es: "Español",
      en: "English",
      remote: "REMOTE",
      menu: "MENU",
    },
    ticker: {
      label: "SIGNALS",
      items: [
        { label: "PRODUCT", value: "Fintech in production" },
        { label: "BASE", value: "Salta · Argentina" },
        { label: "MODE", value: "Full-remote" },
        { label: "OUTPUT", value: "4 public products" },
        { label: "NOW", value: "Building product" },
      ],
    },
    hero: {
      tag: "SALTA · ARGENTINA  //  OPEN TO FULL-REMOTE ROLES",
      identity: "LUCIANO LAZARTE · FULL STACK / PRODUCT",
      title: "I design and build fintech products people can actually use.",
      lead: "Full Stack Developer. Building a retail investing product so people with no prior finance experience can invest. React and TypeScript on the frontend, NestJS and GraphQL on the backend.",
      ctaWork: "SEE WORK",
      ctaContact: "GET IN TOUCH",
      consoleLabel: "OPERATOR PROFILE / 01",
      consoleStatus: "VERIFIABLE PROOF",
      portraitRole: "FULL STACK · PRODUCT · FINTECH",
      proof: [
        { value: "IN PROD", label: "Retail investing fintech product" },
        { value: "04", label: "Public products with live demos" },
        { value: "1ST", label: "Puna Tech 2026 · City Track" },
      ],
      model: {
        label: "MODEL / INTERFACE PREVIEW",
        note: "Conceptual visual · not live market information",
        alt: "Conceptual product interface visualization",
      },
      phrases: [
        "I build fintech products full stack, end to end.",
        "React and TypeScript up front. NestJS and GraphQL in the back.",
        "Retail investing for people who have never invested.",
      ],
      meta: [
        { label: "ROLE", val: "Full Stack Developer" },
        { label: "FOCUS", val: "Fintech · Product" },
        { label: "STACK", val: "React · TypeScript · NestJS · GraphQL" },
        { label: "LOCATION", val: "Salta, Argentina" },
        { label: "AVAILABILITY", val: "Full-remote" },
      ],
    },
    about: {
      title: "ABOUT",
      badge: "// PROFILE",
      p1: "I'm a Computer Engineering student at UCASAL and a Full Stack Developer focused on fintech. I've been investing in capital markets for a few years — that gives me real context on which problems are worth solving with software.",
      p2: "I currently work at Poncho Capital as Full Stack Developer, Product. I'm building a retail investing product for people with no prior finance experience: React and TypeScript on the frontend, NestJS and GraphQL on the backend, web flows end to end.",
      p3: "Before that I worked as a freelance Data Analyst (Python, SQL, Power BI). The projects here are ones I built and use myself.",
      identity: "IDENTITY",
      photoAlt: "Photo of Luciano Lazarte",
      cards: [
        {
          label: "NOW",
          items: [
            "Retail investing product at Poncho Capital",
            "React and TypeScript on the frontend, NestJS and GraphQL on the backend",
            "End-to-end web flows in a small team",
          ],
        },
        {
          label: "LOOKING FOR",
          items: [
            "Full-remote Full Stack / Product roles",
            "Fintech where the product is actually used",
            "Small teams with end-to-end ownership",
          ],
        },
        {
          label: "EDUCATION",
          items: [
            "Computer Engineering · UCASAL · in progress",
            "Data Scientist · Coderhouse",
            "Data Analytics · Coderhouse",
          ],
        },
      ],
    },
    stats: {
      title: "PROOF OF WORK",
      badge: "// 03 VERIFIABLE SIGNALS",
      items: [
        {
          value: "PROD",
          label: "FINTECH PRODUCT",
          sub: "Poncho Capital · retail investing",
          detail: "End-to-end web flows in production",
        },
        {
          value: "04",
          label: "PUBLIC PRODUCTS",
          sub: "Ink · QuantLab · Cello · EstacionaSalta",
          detail: "Live demos, not mockups",
        },
        {
          value: "1st",
          label: "PUNA TECH 2026",
          sub: "City Track · EstacionaSalta",
          detail: "Measured-parking product for Salta",
        },
      ],
    },
    github: {
      title: "ACTIVITY",
      badge: "// GITHUB · JEHP23",
      contributions: "CONTRIBUTIONS · LAST 12 MONTHS",
      chartAlt: "GitHub contribution chart",
      repos: (n: number) => `${n} public repos`,
      since: (year: string) => `active since ${year}`,
      languages: "LANGUAGES",
      recent: "RECENT ACTIVITY",
      today: "today",
      yesterday: "yesterday",
      days: (n: number) => `${n}d ago`,
      weeks: (n: number) => `${n}w ago`,
      months: (n: number) => `${n}mo ago`,
    },
    projects: {
      title: "WORK & FOCUS",
      badge: "// WHAT I BUILD",
      intro: "Selected work, ordered by product impact: from production flows to public experiments you can actually try.",
      caseLabel: "Main case studies",
      selectedLabel: "SELECTED PRODUCTS",
      archiveLabel: "ARCHIVE / LAB",
      items: [
        {
          id: "poncho",
          rarity: "legendary",
          tag: "FLAGSHIP · PRODUCTION",
          title: "Poncho Capital · Retail Investing",
          desc: "An investing product for people with no prior finance experience. I ship the stack end to end in a small team: React and TypeScript on the frontend, NestJS and GraphQL on the backend. Web flows in production.",
          stack: ["React", "TypeScript", "NestJS", "GraphQL"],
          stats: [
            { s: "ROLE", v: "FULL STACK" },
            { s: "STATUS", v: "IN PROD" },
          ],
          links: [{ label: "Site", href: "https://ponchocapital.com" }],
        },
        {
          id: "estacionasalta",
          rarity: "legendary",
          tag: "1ST PUNA TECH 2026 · CITY TRACK",
          title: "EstacionaSalta · Measured parking",
          desc: "Measured-parking product for the city of Salta. First place at Puna Tech 2026, City Track.",
          stack: ["TypeScript", "React", "Next.js"],
          stats: [
            { s: "AWARD", v: "1ST PLACE" },
            { s: "TRACK", v: "CITY" },
          ],
          links: [
            { label: "Demo", href: "https://estacionasalta.vercel.app" },
            { label: "Video", href: "https://www.youtube.com/watch?v=ThcJASSvIPU" },
          ],
        },
        {
          id: "ink",
          rarity: "epic",
          tag: "AVALANCHE · FINTECH",
          title: "INK · Smart Contract Risk Intelligence",
          desc: "Smart-contract risk analyzer. Paste an address and get a deterministic 0–100 score plus a plain-language explanation.",
          stack: ["Next.js", "TypeScript", "Avalanche"],
          stats: [
            { s: "TYPE", v: "LIVE PRODUCT" },
            { s: "SCORE", v: "0–100" },
          ],
          links: [
            { label: "Demo", href: "https://ink-three-iota.vercel.app" },
            { label: "GitHub", href: "https://github.com/Jehp23/ink-risk-intelligence" },
          ],
        },
        {
          id: "cello",
          rarity: "epic",
          tag: "AVALANCHE · PAYMENTS",
          title: "Cello · Institutional payments",
          desc: "Private institutional payments using eERC20 on Avalanche.",
          stack: ["TypeScript", "Avalanche", "eERC20"],
          stats: [
            { s: "TYPE", v: "LIVE PRODUCT" },
            { s: "NETWORK", v: "AVALANCHE" },
          ],
          links: [{ label: "Demo", href: "https://cello-avax.vercel.app" }],
        },
        {
          id: "quantlab",
          rarity: "epic",
          tag: "FINTECH · RESEARCH",
          title: "QuantLab · Quant Research Platform",
          desc: "Quant research platform: VaR, Monte Carlo, efficient frontier, and BYMA options.",
          stack: ["FastAPI", "Python", "Next.js", "TypeScript"],
          stats: [
            { s: "MARKET", v: "ARG + GLOBAL" },
            { s: "MODULES", v: "VAR · MC · BYMA" },
          ],
          links: [
            { label: "Demo", href: "https://quantlab2.vercel.app" },
            { label: "Backend", href: "https://github.com/Jehp23/quantlab-back" },
            { label: "Frontend", href: "https://github.com/Jehp23/quantlab-front" },
          ],
        },
        {
          id: "credit",
          rarity: "rare",
          tag: "DATA SCIENCE · ML",
          title: "Credit Risk · ML Ensemble",
          desc: "Loan default prediction: EDA, SMOTE, PCA, and an ensemble of XGBoost, Random Forest, Gradient Boosting, and a Voting Classifier. AUC 0.942.",
          stack: ["Python", "XGBoost", "scikit-learn", "SMOTE"],
          stats: [
            { s: "AUC", v: "0.942" },
            { s: "MODELS", v: "4 + ENSEMBLE" },
          ],
          links: [
            { label: "GitHub", href: "https://github.com/Jehp23/riesgo-crediticio" },
          ],
        },
      ],
    },
    timeline: {
      title: "EXPERIENCE & EDUCATION",
      badge: "// PATH",
      items: [
        {
          id: "poncho",
          yr: "Mar 2026 · Present",
          role: "Full Stack Developer, Product · Poncho Capital",
          desc: "Building a retail investing product so people with no prior finance experience can invest. I ship features end to end: React and TypeScript on the frontend, NestJS and GraphQL on the backend.",
          tags: ["React", "TypeScript", "NestJS", "GraphQL"],
        },
        {
          id: "freelance",
          yr: "Nov 2024 – Jul 2026",
          role: "Data Analyst · Freelance",
          desc: "Analysis and dashboards in Python, SQL, and Power BI. Turned raw datasets into reports used for financial and operational decisions.",
          tags: ["Python", "SQL", "Power BI"],
        },
        {
          id: "own",
          yr: "2025 · 2026",
          role: "Own projects · Fintech and product",
          desc: "INK (smart-contract risk), QuantLab (quant research), Cello (private institutional payments), and EstacionaSalta (1st place, Puna Tech 2026 · City Track).",
          tags: ["TypeScript", "Avalanche", "Python", "Product"],
        },
        {
          id: "coderhouse",
          yr: "Jun 2024 · Nov 2023",
          role: "Data Scientist · Data Analytics · Coderhouse",
          desc: "Training in ML, applied statistics, exploratory analysis, and data storytelling. A base for working with market numbers without making them up.",
          tags: ["Python", "SQL", "Power BI", "ML"],
        },
        {
          id: "ucasal",
          yr: "2023 – 2028",
          role: "Computer Engineering · UCASAL",
          desc: "In progress. Fundamentals: data structures, algorithms, operating systems, software architecture, and networks.",
          tags: ["CS", "Algorithms", "Systems", "Architecture"],
        },
      ],
    },
    contact: {
      eyebrow: "SHALL WE BUILD SOMETHING THAT MATTERS?",
      title: "Let's talk product, not just tickets.",
      body: "Open to full-remote Full Stack / Product roles in fintech. React, TypeScript, NestJS, GraphQL. If you're building a real product, write me.",
      blink: "OPEN TO FULL-REMOTE ROLES · CURRENTLY AT PONCHO CAPITAL",
    },
    footer: {
      updated: "Updated",
    },
    optimizerCta: {
      label: "PRODUCT LAB · PLAYABLE PROOF",
      title: "I won't just tell you how I think about product. Try it.",
      desc: "Enter your assets with their current weights, see the mix, and we compute the optimal allocation using Markowitz theory and Monte Carlo.",
      button: "OPTIMIZE PORTFOLIO →",
      points: [
        "Mean-variance model",
        "8,000 Monte Carlo simulations",
        "Educational tool with ARS data",
      ],
      previewLabel: "MODEL / INTERFACE PREVIEW",
      previewMode: "STATIC PREVIEW",
      previewAlt: "Conceptual preview of the optimizer's efficient frontier",
      previewStats: [
        { label: "SIMULATIONS", value: "8,000" },
        { label: "MODEL", value: "MARKOWITZ" },
        { label: "SCOPE", value: "EDUCATIONAL" },
      ],
      close: "Close optimizer",
    },
    opt: {
      title: "PORTFOLIO OPTIMIZER",
      badge: "// MARKOWITZ · EFFICIENT FRONTIER",
      intro: (n: string, days: number) =>
        `Mean-variance model (Markowitz, 1952) · ${n} Monte Carlo simulations · Annualized log returns (${days} days) · Prices in ARS · Source: data912.com`,
      composition: "CURRENT MIX",
      asset: "ASSET",
      weight: "WEIGHT (%)",
      placeholder: "e.g. GGAL",
      add: "+ Add asset",
      rf: "ANNUAL RISK-FREE RATE (rf)",
      rfUnit: "% nominal annual",
      rfHint: "For ARS assets, use the BCRA reference rate or LECAP yield.",
      calc: "COMPUTE EFFICIENT FRONTIER →",
      calculating: "COMPUTING...",
      needMore: (n: string) => `${n}pp left to complete the portfolio.`,
      tooMuch: (n: string) => `Portfolio is over 100% by ${n}pp.`,
      minAssets: "Enter at least 2 assets.",
      errMin: "You need at least 2 assets.",
      errWeights: (n: string) => `Weights must add up to 100%. Now: ${n}%.`,
      errData: "Could not fetch data.",
      errConn: "Connection error. Try again.",
      supports:
        "Supports BYMA stocks (GGAL, YPFD, BMA…), CEDEARs (AAPL, MSFT, TSLA…), and sovereign bonds (AL30, GD30…).",
      distribution: "CURRENT DISTRIBUTION",
      stats: "INDIVIDUAL STATS · ASSETS",
      statHeaders: [
        "ASSET",
        "EXPECTED RETURN (E[r])",
        "STD. DEV. (σ)",
        "INDIVIDUAL SHARPE",
        "CURRENT WEIGHT",
      ],
      currentPortfolio: "CURRENT PORTFOLIO",
      sharpeNote: (rf: string, days: number) =>
        `Sharpe = (E[r] − rf) / σ · rf = ${rf} · Annualized log returns over ${days} daily observations.`,
      corr: "CORRELATION MATRIX",
      corrNote:
        "Pearson correlations on daily log returns. Values near 0 mean more diversification benefit.",
      frontier: "EFFICIENT FRONTIER · RISK-RETURN SPACE",
      frontierNote:
        "Each point is a portfolio with random weights. Color: red (low Sharpe) → green (high Sharpe). The CML connects the risk-free rate to the tangency portfolio — points on the CML are unreachable without leverage.",
      recs: "SUGGESTED PORTFOLIOS",
      recItems: [
        { label: "★ TANGENCY PORTFOLIO", sub: "Maximum Sharpe ratio" },
        { label: "◆ MODERATE PORTFOLIO", sub: "Mid Sharpe" },
        { label: "● GLOBAL MIN. VARIANCE", sub: "Lowest risk (GMV)" },
      ],
      disclaimer:
        "Optimization based on ~12 months of historical returns. Past returns do not guarantee future results. Not investment advice. Educational tool.",
      chartYours: "YOUR PORTFOLIO",
      chartX: "RISK — ANNUALIZED STANDARD DEVIATION",
      chartY: "EXPECTED ANNUALIZED RETURN",
      chartLegend: [
        "★  Tangency portfolio (Max Sharpe)",
        "●  Global Minimum Variance (GMV)",
        "●  Moderate portfolio",
        "○  Your current portfolio",
        "- -  Capital Market Line (CML)",
      ],
    },
  },
} as const;
